# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

regression_2 <- function(sigma, patterns, targets, example) {
    .Call(`_tsfgrnn_regression_2`, sigma, patterns, targets, example)
}

build_examples2 <- function(timeS, lags, nt) {
    .Call(`_tsfgrnn_build_examples2`, timeS, lags, nt)
}

build_examples_m <- function(timeS, lags, nt) {
    .Call(`_tsfgrnn_build_examples_m`, timeS, lags, nt)
}

build_examples_a <- function(timeS, lags, nt) {
    .Call(`_tsfgrnn_build_examples_a`, timeS, lags, nt)
}

