# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

regression_2 <- function(sigma, patterns, targets, example) {
    .Call(`_tsfgrnn_regression_2`, sigma, patterns, targets, example)
}

